// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Product service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "List of products",
            "schema": {
              "$ref": "#/definitions/ProductsResponse"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewProduct"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product is added to database",
            "schema": {
              "$ref": "#/definitions/ProductAdded"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Product info",
            "schema": {
              "$ref": "#/definitions/ProductResponse"
            }
          },
          "400": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "Invalid request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "NewProduct": {
      "properties": {
        "description": {
          "title": "NewProduct.description",
          "type": "string"
        },
        "price": {
          "title": "NewProduct.price",
          "type": "number"
        },
        "title": {
          "title": "NewProduct.title",
          "type": "string"
        }
      },
      "required": [
        "description",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "NewProduct",
      "type": "object"
    },
    "ProductsResponse": {
      "properties": {
        "body": {
          "items": {
            "$ref": "#/definitions/Product",
            "title": "ProductsResponse.body.[]"
          },
          "title": "ProductsResponse.body",
          "type": "array"
        },
        "headers": {
          "properties": {
            "'Access-Control-Allow-Origin'": {
              "title": "ProductsResponse.headers.'Access-Control-Allow-Origin'",
              "type": "string"
            },
            "'Access-Control-Allow-Headers'": {
              "title": "ProductsResponse.headers.'Access-Control-Allow-Headers'",
              "type": "string"
            }
          },
          "required": [
            "'Access-Control-Allow-Origin'",
            "'Access-Control-Allow-Headers'"
          ],
          "additionalProperties": false,
          "title": "ProductsResponse.headers",
          "type": "object"
        }
      },
      "required": [
        "body",
        "headers"
      ],
      "additionalProperties": false,
      "title": "ProductsResponse",
      "type": "object"
    },
    "ProductResponse": {
      "properties": {
        "body": {
          "$ref": "#/definitions/Product",
          "title": "ProductResponse.body"
        },
        "headers": {
          "properties": {
            "'Access-Control-Allow-Origin'": {
              "title": "ProductResponse.headers.'Access-Control-Allow-Origin'",
              "type": "string"
            },
            "'Access-Control-Allow-Headers'": {
              "title": "ProductResponse.headers.'Access-Control-Allow-Headers'",
              "type": "string"
            }
          },
          "required": [
            "'Access-Control-Allow-Origin'",
            "'Access-Control-Allow-Headers'"
          ],
          "additionalProperties": false,
          "title": "ProductResponse.headers",
          "type": "object"
        }
      },
      "required": [
        "body",
        "headers"
      ],
      "additionalProperties": false,
      "title": "ProductResponse",
      "type": "object"
    },
    "ProductAdded": {
      "properties": {
        "id": {
          "title": "ProductAdded.id",
          "type": "string"
        },
        "headers": {
          "properties": {
            "'Access-Control-Allow-Origin'": {
              "title": "ProductAdded.headers.'Access-Control-Allow-Origin'",
              "type": "string"
            },
            "'Access-Control-Allow-Headers'": {
              "title": "ProductAdded.headers.'Access-Control-Allow-Headers'",
              "type": "string"
            }
          },
          "required": [
            "'Access-Control-Allow-Origin'",
            "'Access-Control-Allow-Headers'"
          ],
          "additionalProperties": false,
          "title": "ProductAdded.headers",
          "type": "object"
        }
      },
      "required": [
        "id",
        "headers"
      ],
      "additionalProperties": false,
      "title": "ProductAdded",
      "type": "object"
    },
    "ErrorResponse": {
      "properties": {
        "statusCode": {
          "title": "ErrorResponse.statusCode",
          "type": "number"
        },
        "error": {
          "title": "ErrorResponse.error",
          "type": "string"
        }
      },
      "required": [
        "statusCode",
        "error"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};